### ISSUE TITLE
ONT direct RNA minimap2 output seg faults on while parsing chromosomes

### ISSUE THREAD

**Issue by biobenkj** [fritzsedlazeck/Sniffles#161] opened 2019-09-05 17:57 UTC
Hi Fritz,

Thanks for writing sniffles! I was trying to use minimap2 output as input to sniffles. This is an Ewings-sarcoma cell line so we are hoping to see the EWS-FLI1 fusion from our ONT direct RNA output.

minimap2 call:

```
minimap2 --MD -t 16 -ax splice -uf -k14 GRCh38_full_analysis_set_plus_decoy_hla.fa chla10_merged_reads.fastq.gz | samtools sort -o chla10_merged_reads.sorted.bam -O BAM -
[M::mm_idx_gen::77.898*1.95] collected minimizers
[M::mm_idx_gen::88.262*3.41] sorted minimizers
[M::main::88.263*3.41] loaded/built the index for 3366 target sequence(s)
[M::mm_mapopt_update::90.897*3.34] mid_occ = 2059
[M::mm_idx_stat] kmer size: 14; skip: 5; is_hpc: 0; #seq: 3366
[M::mm_idx_stat::91.843*3.32] distinct minimizers: 65673637 (22.55% are singletons); average occurrences: 15.767; average spacing: 3.107
[M::worker_pipeline::173.651*8.19] mapped 220505 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 --MD -t 16 -ax splice -uf -k14 GRCh38_full_analysis_set_plus_decoy_hla.fa chla10_merged_reads.fastq.gz
[M::main] Real time: 174.023 sec; CPU: 1422.583 sec; Peak RSS: 18.908 GB
```
sniffles call and output:

```
sniffles -m chla10_merged_reads.sorted.bam -v chla10_merged_reads.sniffles.vcf
Estimating parameter...
	Max dist between aln events: 70
	Max diff in window: 50
	Min score ratio: 2
	Avg DEL ratio: 0.027756
	Avg INS ratio: 0.0107768
Start parsing... chr1
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 7227) > this->size() (which is 1765)
Aborted (core dumped)
```

Have you encountered this before or could shed some light on the issue?

Thanks for your time!

Ben

**Comment by fritzsedlazeck** [comment] 2019-09-05 18:00
Sorry haven't seen that before. Can you share? Fritz.sedlazeck@gmail.com ?
Just a couple of alignments is also fine.
Thanks
Fritz

**Comment by biobenkj** [comment] 2019-09-05 21:37
To follow-up, I uploaded the bam and index and sent you an e-mail. Please let me know if you didn't get it. Thanks again!

**Comment by fritzsedlazeck** [comment] 2019-09-05 21:41
Thanks got it. 
Cheers
Fritz

**Comment by fritzsedlazeck** [comment] 2019-09-05 22:28
I looked at it. I think the problem is that you dont have any read sequence in the bam file. I am looking further to see if I can give an error so users will know what is happening. 
However, that is currently my best guess. 
Cheers
Fritz

**Comment by fritzsedlazeck** [comment] 2019-09-05 22:35
Ok I committed a fix for this. Unfortunately, you need to check why your bam file does not include read sequence information. I do need that information to reconstruct the insertion sequence. 

I am going to close this, but please reach out if it does not work. 

Thanks again for reporting this. 
Fritz

**Closed by fritzsedlazeck** 2019-09-05 22:35 UTC

**Comment by biobenkj** [comment] 2019-11-15 15:32
@fritzsedlazeck would you be open to some sort of collaboration with the @trichelab to get this rolling for Sniffles to do calling on direct RNA? Thanks!

**Comment by fritzsedlazeck** [comment] 2019-11-15 15:44
You mean RNA fusion calling with Sniffles?
Lets take this offline: fritz.sedlazeck@gmail.com

**Comment by sunshine-lp0** [comment] 2020-10-13 07:09
> @fritzsedlazeck would you be open to some sort of collaboration with the @trichelab to get this rolling for Sniffles to do calling on direct RNA? Thanks!
Dear Ben,
Can you work with sniffles using long-red RNA-seq data now ?
Thanks very much!

**Comment by fritzsedlazeck** [comment] 2020-10-13 12:02
Hey,
Sure we can take a look. Best would be if you ping me at fritz.sedlazeck@gmail.com
Cheers
Fritz

**Comment by biobenkj** [comment] 2020-10-14 14:59
Will also follow up with an email @fritzsedlazeck @sunshine-lp0 

We have a strong interest in being able to resolve SVs with ONT direct RNA using Sniffles

**Comment by sunshine-lp0** [comment] 2020-10-16 01:35
> Will also follow up with an email @fritzsedlazeck @sunshine-lp0
> 
> We have a strong interest in being able to resolve SVs with ONT direct RNA using Sniffles

Thanks a lot!

**Comment by wijerasa** [comment] 2020-12-18 19:25
I was wondering if Sniffles is ready for RNASeq data coming out of ISO-seq pipeline. I'm having similar issue.
`sniffles -r 200 -m minimap2/cupcake.collapsed.min_fl_2.filtered_mapped_hg38_sorted.bam -v test_run3a.vcf
Estimating parameter...
	Max dist between aln events: 1094
	Max diff in window: 80
	Min score ratio: 2
	Avg DEL ratio: 0.000388833
	Avg INS ratio: 0.000741945
Start parsing... chr1
Read sequence is shorter than expected. Please check your bam file if the read sequence is reported!`

Any help would be greatly appreciated.

Thanks!
Saranga

**Comment by fritzsedlazeck** [comment] 2020-12-18 19:48
Thanks that's interesting. I will need to check the alignments.. 
Cheers
Fritz
