### ISSUE TITLE
not finding all very obvious INS with 20x coverage and 40 read support

### ISSUE THREAD

**Issue by FiniDG-HAN** [fritzsedlazeck/Sniffles#107] opened 2018-10-12 12:51 UTC
I am testing Sniffles for a small school project. I was getting some unexpected results, so I tried to make a very simple dataset to see how the start/stop/size positions worked exactly.
I used:
- 1MB region of the Arabidopsis thaliana reference genome
- Manually put 30 INS of size 100 after every 30000 reads with a random DNA seq (random DNA generator with GC content conform the organism)
- Manually made reads of the edited 1MB region, with 20x coverage (I just cut pieces of 10kb with a python script, so no errors in the reads)
- Mapped the reads back to original 1MB ref genome with NGMLR

Only 24 INS are found back. Using a genome viewer (Tablet or IGV) of the .sam file of the NGMLR mapping, you clearly see all 30 INS and they all call for 100 size, so I was wondering why Sniffles does not find all INS? I also tried using the -s parameter 5 as minimal read support, but that doesn't work and additionally all the found 24 INS have read support of 38 and 40, so that shouldn't even be the problem. Are there other parameters I could try?

**Comment by fritzsedlazeck** [comment] 2018-10-12 12:55
Hey thanks for reaching out. Can you share the bam file? 
Sniffles has some filtering methods for too noisy reads and too noisy calls. You can control these, but I agree based on what you say it should be able to find it. It would be nice to take a look.
Thanks
Fritz

**Comment by FiniDG-HAN** [comment] 2018-10-12 12:56
How should I provide the files?

**Comment by fritzsedlazeck** [comment] 2018-10-12 13:01
please just email them over: fritz.sedlazeck@gmail.com

**Comment by fritzsedlazeck** [comment] 2018-10-12 13:20
I just had a quick look. The observation is that I think given that there is no seq. error in the reads Sniffles is a bit suspicious or gets confused. Using --skip_parameter_estimation gets 28 out of the 30 ins. I will investigate further, but that is likely the cause. Thanks for sharing the data.

**Comment by FiniDG-HAN** [comment] 2018-10-12 13:27
No problem! I was just using this data to test the vcf output, because sometimes I had trouble with interpreting the start/stop/size positions and with this dataset I was hoping to get more conclusive evidence about that, which I can also do with the 24 positive results. I was just wondering why the other 6 were not found, while they were very obvious.
Let me know what your findings are.

**Comment by fritzsedlazeck** [comment] 2018-10-12 13:28
Yes thanks for reaching out! 
Fritz

**Comment by FiniDG-HAN** [comment] 2018-10-12 13:55
To update this. I made another readset with PBSIM. With the same read length and coverage (10.000 and 20x), min and max read length also 10.000, but with around 0.85 accuracy.
And indeed, Sniffles now finds 28, without adding any parameters. So I believe the reason why my INS were not found was indeed because of the unrealistic (too good to be true) situation. I think if I use normal read length distributions it will improve further.

Sorry for the topic and thanks for your help

**Comment by fritzsedlazeck** [comment] 2018-10-12 14:03
Thanks again for reaching out. I will close this now, but I will have a look at the remaining 2.
Cheers
Fritz

**Closed by fritzsedlazeck** 2018-10-12 14:03 UTC

**Comment by fritzsedlazeck** [comment] 2018-10-16 13:48
Mhm this is very strange. Can you again send me a bam file?
Thanks
Fritz

**Comment by FiniDG-HAN** [comment] 2018-10-17 07:04
The files are too big (35Mb-NGMLR and 60Mb-MiniMap)

**Comment by fritzsedlazeck** [comment] 2018-10-17 15:17
Can you use samtools to extract a few regions where the mutations are?
samtools view -hb your.bam chr1:start-stop > region.bam

Thanks
Fritz
